-- ============================================================================
-- SIH26183 : relational schema (PostgreSQL 16)
-- Runs once, on first container start, from /docker-entrypoint-initdb.d.
--
-- SCOPE NOTE: every row this schema will ever hold in this prototype is either
-- synthetic (generated by scripts/generate_synthetic_complaints.py) or drawn
-- from public datasets. There is no real NCRP complaint data and no real
-- exchange KYC data in this system.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enumerated domains
-- ---------------------------------------------------------------------------
CREATE TYPE chain_t          AS ENUM ('BTC', 'ETH', 'TRON');
CREATE TYPE user_role_t      AS ENUM ('investigator', 'supervisor', 'admin');
CREATE TYPE case_status_t    AS ENUM ('open', 'tracing', 'analysed', 'escalated', 'closed');
CREATE TYPE wallet_role_t    AS ENUM ('reported_suspect', 'intermediate', 'terminal');
CREATE TYPE entity_type_t    AS ENUM ('exchange', 'mixer', 'gambling', 'darknet',
                                      'sanctioned', 'payment_processor', 'unknown');
CREATE TYPE risk_label_t     AS ENUM ('low', 'medium', 'high');
CREATE TYPE trace_status_t   AS ENUM ('queued', 'running', 'complete', 'failed');
CREATE TYPE attribution_m_t  AS ENUM ('tagged_db', 'classifier', 'manual', 'none');

-- Human-in-the-loop lifecycle. A freeze request can ONLY reach 'approved' via
-- an explicit action by a user whose role is 'supervisor'. Nothing in this
-- system transitions a freeze request automatically.
CREATE TYPE approval_t       AS ENUM ('draft', 'pending_approval', 'approved',
                                      'rejected', 'dispatched');

-- ---------------------------------------------------------------------------
-- Identity & audit
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username        TEXT NOT NULL UNIQUE,
    full_name       TEXT NOT NULL,
    email           TEXT UNIQUE,
    hashed_password TEXT NOT NULL,
    role            user_role_t NOT NULL DEFAULT 'investigator',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE audit_log (
    id          BIGSERIAL PRIMARY KEY,
    actor_id    UUID REFERENCES users(id),
    action      TEXT NOT NULL,             -- e.g. freeze_request.approve
    entity_type TEXT NOT NULL,
    entity_id   TEXT,
    payload     JSONB NOT NULL DEFAULT '{}'::jsonb,
    ip_address  INET,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_entity  ON audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_log (created_at DESC);

-- ---------------------------------------------------------------------------
-- Wallet registry  (one row per address, shared across all cases)
-- ---------------------------------------------------------------------------
CREATE TABLE wallets (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    address        TEXT NOT NULL,          -- as supplied by the victim
    address_norm   TEXT NOT NULL,          -- lowercased for ETH, verbatim for BTC/TRON
    chain          chain_t NOT NULL,
    address_kind   TEXT,                   -- p2pkh | p2sh | bech32 | eoa | contract | tron_base58
    first_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_traced_at TIMESTAMPTZ,
    report_count   INTEGER NOT NULL DEFAULT 0,   -- multi-victim signal (see cases)
    CONSTRAINT uq_wallet_chain_addr UNIQUE (chain, address_norm)
);
CREATE INDEX idx_wallets_norm ON wallets (address_norm);

-- ---------------------------------------------------------------------------
-- Complaints / cases
-- ---------------------------------------------------------------------------
CREATE TABLE cases (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_number TEXT NOT NULL UNIQUE,            -- internal, e.g. SIH183-2026-000001
    ncrp_ref    TEXT,                            -- MOCK NCRP/1930 acknowledgement id
    source      TEXT NOT NULL DEFAULT 'manual',  -- manual | ncrp_mock | synthetic
    status      case_status_t NOT NULL DEFAULT 'open',
    victim_ref  TEXT,                            -- pseudonymous handle only; never PII
    amount_inr  NUMERIC(18, 2),
    reported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    narrative   TEXT,
    created_by  UUID REFERENCES users(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_cases_status   ON cases (status);
CREATE INDEX idx_cases_reported ON cases (reported_at DESC);

-- A case may implicate several addresses; an address may appear in many cases.
-- The (wallet_id, role='reported_suspect') fan-out IS the dedupe/fraud-ring
-- signal: N distinct cases pointing at one wallet.
CREATE TABLE case_wallets (
    case_id   UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    wallet_id UUID NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
    role      wallet_role_t NOT NULL DEFAULT 'reported_suspect',
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (case_id, wallet_id, role)
);
CREATE INDEX idx_case_wallets_wallet ON case_wallets (wallet_id);

-- ---------------------------------------------------------------------------
-- VASP / entity intelligence
-- ---------------------------------------------------------------------------
CREATE TABLE entities (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name         TEXT NOT NULL,
    entity_type  entity_type_t NOT NULL DEFAULT 'unknown',
    jurisdiction TEXT,
    website      TEXT,
    notes        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_entity_name_type UNIQUE (name, entity_type)
);

-- Seeded from PUBLIC sources only: Etherscan Label Cloud, WalletExplorer,
-- GraphSense TagPacks, OFAC SDN crypto address list. `source` is mandatory so
-- every attribution shown in the UI can cite where the tag came from.
CREATE TABLE tagged_addresses (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    address_norm TEXT NOT NULL,
    chain        chain_t NOT NULL,
    entity_id    UUID NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    label        TEXT,                    -- e.g. Binance hot wallet 7
    source       TEXT NOT NULL,           -- ofac_sdn | etherscan_labels | tagpacks | walletexplorer
    confidence   REAL NOT NULL DEFAULT 1.0 CHECK (confidence BETWEEN 0 AND 1),
    added_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_tag_chain_addr UNIQUE (chain, address_norm, source)
);
CREATE INDEX idx_tagged_lookup ON tagged_addresses (chain, address_norm);

-- Mirror of the cluster identity that Neo4j owns. Neo4j is the source of truth
-- for membership; Postgres keeps the id so scores and reports can key off it.
CREATE TABLE clusters (
    id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cluster_key            TEXT NOT NULL UNIQUE,   -- deterministic, assigned in Neo4j
    chain                  chain_t NOT NULL,
    heuristic              TEXT NOT NULL,          -- common_input_ownership | change_address | account_single
    size                   INTEGER NOT NULL DEFAULT 1,
    entity_id              UUID REFERENCES entities(id),
    attribution_method     attribution_m_t NOT NULL DEFAULT 'none',
    attribution_confidence REAL CHECK (attribution_confidence BETWEEN 0 AND 1),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Tracing
-- ---------------------------------------------------------------------------
CREATE TABLE trace_runs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id             UUID REFERENCES cases(id) ON DELETE CASCADE,
    root_wallet_id      UUID NOT NULL REFERENCES wallets(id),
    max_depth           INTEGER NOT NULL DEFAULT 6,
    status              trace_status_t NOT NULL DEFAULT 'queued',
    hops_discovered     INTEGER NOT NULL DEFAULT 0,
    addresses_touched   INTEGER NOT NULL DEFAULT 0,
    mixer_interaction   BOOLEAN NOT NULL DEFAULT FALSE,  -- flagged, never "broken"
    terminal_cluster_id UUID REFERENCES clusters(id),
    data_source         TEXT NOT NULL DEFAULT 'synthetic', -- synthetic | etherscan | trongrid | blockchair
    error               TEXT,
    started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at         TIMESTAMPTZ
);
CREATE INDEX idx_trace_case ON trace_runs (case_id);

-- ---------------------------------------------------------------------------
-- Fraud-linkage risk scoring (explainable by construction)
-- ---------------------------------------------------------------------------
CREATE TABLE risk_scores (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_id      UUID REFERENCES entities(id) ON DELETE CASCADE,
    cluster_id     UUID REFERENCES clusters(id) ON DELETE CASCADE,
    score          NUMERIC(5,2) NOT NULL CHECK (score BETWEEN 0 AND 100),
    label          risk_label_t NOT NULL,
    half_life_days INTEGER NOT NULL,
    model_version  TEXT NOT NULL,
    computed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_risk_target CHECK (entity_id IS NOT NULL OR cluster_id IS NOT NULL)
);
CREATE INDEX idx_risk_entity ON risk_scores (entity_id, computed_at DESC);

-- One row per case that pushed a score up. This table is what the dashboard
-- renders beneath the number, so the score is never a bare black-box output.
CREATE TABLE risk_contributions (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    risk_score_id    UUID NOT NULL REFERENCES risk_scores(id) ON DELETE CASCADE,
    case_id          UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    terminal_address TEXT,
    age_days         INTEGER NOT NULL,
    decay_weight     REAL NOT NULL,          -- 0.5 ^ (age_days / half_life_days)
    points           NUMERIC(6,3) NOT NULL   -- this case's contribution to score
);
CREATE INDEX idx_contrib_score ON risk_contributions (risk_score_id);

-- ---------------------------------------------------------------------------
-- Case work product
-- ---------------------------------------------------------------------------
CREATE TABLE case_notes (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id    UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    author_id  UUID REFERENCES users(id),
    body       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE evidence (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id      UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    filename     TEXT NOT NULL,
    content_type TEXT,
    size_bytes   BIGINT NOT NULL,
    sha256       CHAR(64) NOT NULL,      -- chain-of-custody digest
    storage_path TEXT NOT NULL,
    uploaded_by  UUID REFERENCES users(id),
    uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_evidence_case ON evidence (case_id);

CREATE TABLE reports (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id      UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    kind         TEXT NOT NULL,          -- forensic_pdf | str_draft
    sha256       CHAR(64) NOT NULL,
    storage_path TEXT NOT NULL,
    generated_by UUID REFERENCES users(id),
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Human-in-the-loop actions
-- ---------------------------------------------------------------------------
CREATE TABLE freeze_requests (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id          UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    entity_id        UUID REFERENCES entities(id),
    target_address   TEXT NOT NULL,
    amount_inr       NUMERIC(18,2),
    justification    TEXT NOT NULL,
    status           approval_t NOT NULL DEFAULT 'draft',
    requested_by     UUID REFERENCES users(id),
    -- approved_by MUST be a distinct user holding the supervisor role; that is
    -- enforced in the service layer and asserted by tests. No code path sets
    -- these columns without an explicit approval click in the UI.
    approved_by      UUID REFERENCES users(id),
    approved_at      TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_freeze_approved_needs_actor
        CHECK (status <> 'approved' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL))
);
CREATE INDEX idx_freeze_status ON freeze_requests (status);

CREATE TABLE str_drafts (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id     UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    entity_id   UUID REFERENCES entities(id),
    body        TEXT NOT NULL,
    status      approval_t NOT NULL DEFAULT 'draft',
    created_by  UUID REFERENCES users(id),
    approved_by UUID REFERENCES users(id),
    approved_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Alerts (mirrored from the Redis Stream so the dashboard has history)
-- ---------------------------------------------------------------------------
CREATE TABLE alerts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id         UUID REFERENCES cases(id) ON DELETE CASCADE,
    entity_id       UUID REFERENCES entities(id),
    severity        risk_label_t NOT NULL,
    message         TEXT NOT NULL,
    stream_msg_id   TEXT,
    acknowledged_by UUID REFERENCES users(id),
    acknowledged_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_alerts_created ON alerts (created_at DESC);

-- ---------------------------------------------------------------------------
-- Cross-case view: wallets recurring across complaints (fraud-ring signal)
-- ---------------------------------------------------------------------------
CREATE VIEW v_multi_reported_wallets AS
SELECT w.id                       AS wallet_id,
       w.address,
       w.chain,
       COUNT(DISTINCT cw.case_id) AS case_count,
       MIN(c.reported_at)         AS first_reported_at,
       MAX(c.reported_at)         AS last_reported_at
FROM wallets w
JOIN case_wallets cw ON cw.wallet_id = w.id
JOIN cases c         ON c.id = cw.case_id
GROUP BY w.id, w.address, w.chain
HAVING COUNT(DISTINCT cw.case_id) > 1;
