"""Baseline: the schema as built by infra/postgres SQL.

Revision ID: 0001
Revises:
Created: 2026-09-09

This executes the SQL files that already created every existing database
rather than a schema autogenerated from the models. That choice is deliberate:
autogenerate infers from SQLAlchemy metadata, which is not guaranteed to
reproduce the enum types, check constraints and indexes the hand-written SQL
actually created. A baseline that differs from the deployed schema makes every
later diff a comparison against a fiction.

For a database that already exists, do not run this - stamp it instead:

    alembic stamp 0001

`scripts/migrate.py` does that automatically when it detects existing tables.
"""

from __future__ import annotations

from pathlib import Path

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None

#: Applied in order. 001 creates the core schema; 002 adds the service-exposure
#: tables, which were written after the first databases already existed.
SQL_FILES = ("init.sql", "002_exposure.sql")

_SEARCH_PATHS = (
    Path("/app/infra/postgres"),
    Path(__file__).resolve().parents[3] / "infra" / "postgres",
)


def _sql_dir() -> Path:
    for candidate in _SEARCH_PATHS:
        if candidate.exists():
            return candidate
    raise RuntimeError(
        f"could not find the postgres SQL directory in any of: "
        f"{[str(p) for p in _SEARCH_PATHS]}"
    )


def upgrade() -> None:
    directory = _sql_dir()
    connection = op.get_bind()

    for name in SQL_FILES:
        path = directory / name
        if not path.exists():
            raise RuntimeError(f"baseline SQL file missing: {path}")
        connection.execute(sa.text(path.read_text(encoding="utf-8")))


def downgrade() -> None:
    # Deliberately not implemented. Reversing the baseline means dropping every
    # table, every enum and all case data with them - which is not a migration,
    # it is data destruction wearing one's clothes. Drop the database instead,
    # consciously, if that is really what is wanted.
    raise NotImplementedError(
        "The baseline is not reversible. Dropping it would destroy all case "
        "and evidence data. Drop the database explicitly if that is intended."
    )
