#!/usr/bin/env python3
"""Load the demonstration state: seed tags, then file every synthetic complaint.

Run this after a fresh `docker compose up`, and again after running the test
suite - the test fixtures deliberately clear graph transaction data, so the
traced money flow has to be rebuilt (the seeded tag database survives).

Everything loaded here is synthetic or public-dataset derived. No real NCRP
complaint data and no exchange KYC data is involved.

Every run files the same thirteen complaints again, so case counts, risk scores
and the exchange ranking all climb with each run. `--reset` clears the
case-side data first and gives the numbers a demonstration actually wants -
without touching the seeded tag database, which is reference data that takes
minutes to rebuild.

Usage:
    docker compose exec backend python scripts/load_demo.py
    docker compose exec backend python scripts/load_demo.py --skip-tags
    docker compose exec backend python scripts/load_demo.py --reset
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def seed_tags() -> None:
    print("=== seeding tagged-address database (public sources) ===", flush=True)
    script = Path("/app/ml/src/seed_tags.py")
    if not script.exists():
        script = REPO / "ml" / "src" / "seed_tags.py"
    subprocess.run([sys.executable, str(script)], check=True)


# Deleted in dependency order by --reset. Everything here is produced by
# filing complaints and can be regenerated by re-running this script.
#
# Deliberately NOT listed: `users` (the demo accounts survive, so a browser
# stays signed in), `entities` and `tagged_addresses` (the public tag database
# - reference data, minutes to rebuild, and nothing to do with a demo run).
CASE_TABLES = [
    "exposure_paths",
    "service_exposures",
    "risk_contributions",
    "risk_scores",
    "alerts",
    "str_drafts",
    "freeze_requests",
    "reports",
    "evidence",
    "case_notes",
    "case_wallets",
    "trace_runs",
    "clusters",
    "cases",
    "wallets",
    "audit_log",
]


def reset_case_data() -> None:
    """Clear everything produced by previous demo runs.

    Destructive by design and never the default. Case-side tables only: the tag
    database and the demo user accounts are left alone.
    """
    from sqlalchemy import text

    from app.db.postgres import SessionLocal
    from app.services import graph_writer

    print("=== resetting demonstration data ===", flush=True)

    db = SessionLocal()
    try:
        for table in CASE_TABLES:
            deleted = db.execute(text(f"DELETE FROM {table}")).rowcount  # noqa: S608
            if deleted:
                print(f"  {table:22s} {deleted:6d} row(s) deleted", flush=True)
        db.commit()
    finally:
        db.close()

    # Transaction and address nodes, but not the seeded :Entity tags - the same
    # scoped cleanup the test suite uses.
    graph_writer.clear_test_data()
    print("  neo4j                 transaction graph cleared (tags preserved)", flush=True)


def file_complaints(depth: int | None) -> int:
    from sqlalchemy.orm import Session

    from app.db.postgres import SessionLocal
    from app.services.connectors.synthetic import get_complaints
    from app.services.ingest import intake_wallet

    complaints = get_complaints()
    print(f"\n=== filing {len(complaints)} synthetic complaints ===", flush=True)

    filed = 0
    db: Session = SessionLocal()
    try:
        for c in complaints:
            result = intake_wallet(
                db,
                address=c["address"],
                victim_ref=c["victim_ref"],
                amount_inr=c.get("amount_inr"),
                narrative=c.get("narrative"),
                source="synthetic",
                trace_depth=depth,
            )
            trace = result["trace"]
            print(
                f"  {result['case_number']}  {result['chain']:4s} "
                f"hops={trace['hops_discovered']} addrs={trace['addresses_touched']} "
                f"txs={trace['transactions_ingested']}"
                + ("  [mixer]" if trace["mixer_interaction"] else ""),
                flush=True,
            )
            filed += 1
    finally:
        db.close()
    return filed


def summarise() -> None:
    from app.db.postgres import SessionLocal
    from app.services.risk import rank_entities

    print("\n=== exchange fraud-linkage ranking ===", flush=True)
    db = SessionLocal()
    try:
        for e in rank_entities(db, limit=10):
            print(
                f"  {e['risk_label'].upper():6s} {e['risk_score']:6.2f}  "
                f"{e['case_count']:3d} cases  {e['chain']:4s}  {e['entity_name']}"
            )
    finally:
        db.close()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--skip-tags", action="store_true", help="do not re-seed the tag DB")
    ap.add_argument("--depth", type=int, default=None, help="trace depth override")
    ap.add_argument(
        "--reset",
        action="store_true",
        help="DELETE all cases, wallets, scores and alerts first, so counts start "
        "from zero. Leaves the tag database and demo accounts intact.",
    )
    args = ap.parse_args()

    if args.reset:
        reset_case_data()

    if not args.skip_tags:
        seed_tags()

    filed = file_complaints(args.depth)
    summarise()

    # Printed from the dataset itself. Addresses shift whenever the generator's
    # random draws change, so any address copied into a doc goes stale silently.
    # This is the authoritative list for whoever is about to run the demo.
    print("\n=== addresses to paste into the dashboard ===")
    from app.services.connectors.synthetic import get_complaints

    seen: set[str] = set()
    for complaint in get_complaints():
        if complaint["chain"] in seen:
            continue
        seen.add(complaint["chain"])
        print(f"  {complaint['chain']:5s} {complaint['address']}")

    print(f"\ndemo loaded: {filed} complaints filed.")
    print("All data is SYNTHETIC. Try: curl 'localhost:8001/api/v1/exchanges/ranked'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
